# https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "website/dist"
  command = "cd website && npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build"
